name: Checks

on:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Format
        run: npm run format:check

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Lint
        run: npm run lint -- --max-warnings 0

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Test
        run: npm run test

  may-merge:
    needs: ["format", "lint", "test"]
    runs-on: ubuntu-latest
    steps:
      - name: Cleared for merging
        run: echo OK
