name: Test npm build

on:
  push:
    branches:
      - trusted-publishing

jobs:
  publish-test:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Prepare
        uses: ./.github/actions/prepare

  publish-next-test:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Build next version
        run: ./scripts/build-next
